name: church_of_god_app
description: A mobile and web app for Church of God Evening Light.

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Essentials
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  provider: ^6.1.1

  # Firebase Core & Auth
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5

  # Push Notifications
  firebase_messaging: ^15.2.5

  # Audio
  just_audio: ^0.9.36
  audio_session: ^0.1.16

  # Local Storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.2.5
  connectivity_plus: ^6.1.3

  # State & Routing
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700


